<?php

/**
 * Texts used in the application.
 * These texts are used via Text::get('FEEDBACK_USERNAME_ALREADY_TAKEN').
 * Could be extended to i18n etc.
 */
return array(
    "FEEDBACK_UNKNOWN_ERROR" => "¡Error desconocido!",
    "FEEDBACK_DELETED" => "Tu cuenta ha sido eliminada.",
    "FEEDBACK_ACCOUNT_NO_AUTHORIZED" => "No autorizado",
    "FEEDBACK_ACCOUNT_SUSPENDED" => "Cuenta suspendida por",
    "FEEDBACK_ACCOUNT_SUSPENSION_DELETION_STATUS" => "El estado de suspensión / eliminación de este usuario ha sido editado.",
    "FEEDBACK_ACCOUNT_CANT_DELETE_SUSPEND_OWN" => "No puedes borrar o suspender tu propia cuenta.",
    "FEEDBACK_ACCOUNT_USER_SUCCESSFULLY_KICKED" => "El usuario seleccionado ha sido expulsado con éxito del sistema (restableciendo la sesión de este usuario)",
    "FEEDBACK_PASSWORD_WRONG_3_TIMES" => "Ya ha escrito una contraseña incorrecta 3 o más veces. Por favor, espere 30 segundos para volver a intentarlo.",
    "FEEDBACK_ACCOUNT_NOT_ACTIVATED_YET" => "Tu cuenta aún no está activada. Por favor haga clic en el enlace de confirmación en el correo.",
    "FEEDBACK_USERNAME_OR_PASSWORD_WRONG" => "El nombre de usuario o contraseña son incorrectos. Inténtalo de nuevo.",
    "FEEDBACK_USER_DOES_NOT_EXIST" => "Este usuario no existe.",
    "FEEDBACK_LOGIN_FAILED" => "Error de inicio de sesion.",
    "FEEDBACK_LOGIN_FAILED_3_TIMES" => "El inicio de sesión falló 3 o más veces ya. Por favor, espere 30 segundos para volver a intentarlo.",
    "FEEDBACK_USERNAME_FIELD_EMPTY" => "El campo de nombre de usuario estaba vacío.",
    "FEEDBACK_PASSWORD_FIELD_EMPTY" => "El campo de contraseña estaba vacío.",
    "FEEDBACK_USERNAME_OR_PASSWORD_FIELD_EMPTY" => "El campo de nombre de usuario o contraseña estaba vacío.",
    "FEEDBACK_USERNAME_EMAIL_FIELD_EMPTY" => "El nombre de usuario / campo de correo electrónico estaba vacío",
    "FEEDBACK_EMAIL_FIELD_EMPTY" => "El campo de correo electrónico estaba vacío.",
    "FEEDBACK_EMAIL_REPEAT_WRONG" => "El correo electrónico y la repetición de correo electrónico no son lo mismo",
    "FEEDBACK_EMAIL_AND_PASSWORD_FIELDS_EMPTY" => "Los campos de correo electrónico y contraseña estaban vacíos.",
    "FEEDBACK_USERNAME_SAME_AS_OLD_ONE" => "Lo sentimos, ese nombre de usuario es el mismo que el actual. Por favor elije otro.",
    "FEEDBACK_USERNAME_ALREADY_TAKEN" => "Lo siento, el nombre de usuario ya está en uso. Por favor elije otro.",
    "FEEDBACK_USER_EMAIL_ALREADY_TAKEN" => "Lo sentimos, ese correo electrónico ya está en uso. Por favor elije otro.",
    "FEEDBACK_USERNAME_CHANGE_SUCCESSFUL" => "Su nombre de usuario ha sido cambiado con éxito.",
    "FEEDBACK_USERNAME_AND_PASSWORD_FIELD_EMPTY" => "Los campos de nombre de usuario y contraseña estaban vacíos.",
    "FEEDBACK_USERNAME_DOES_NOT_FIT_PATTERN" => "El nombre de usuario no se ajusta al patrón de nombre: solo se permiten a-Z y números, de 2 a 64 caracteres.",
    "FEEDBACK_EMAIL_DOES_NOT_FIT_PATTERN" => "Lo sentimos, su correo electrónico elegido no encaja en el patrón de nombre de correo electrónico.",
    "FEEDBACK_EMAIL_SAME_AS_OLD_ONE" => "Lo sentimos, esa dirección de correo electrónico es la misma que la actual. Por favor elije otro.",
    "FEEDBACK_EMAIL_CHANGE_SUCCESSFUL" => "Su dirección de correo electrónico se ha cambiado con éxito.",
    "FEEDBACK_CAPTCHA_WRONG" => "Los caracteres de seguridad captcha ingresados estaban equivocados.",
    "FEEDBACK_PASSWORD_REPEAT_WRONG" => "Repetición de contraseña y contraseña no son lo mismo.",
    "FEEDBACK_PASSWORD_TOO_SHORT" => "La contraseña tiene una longitud mínima de 6 caracteres.",
    "FEEDBACK_USERNAME_TOO_SHORT_OR_TOO_LONG" => "El nombre de usuario no puede tener menos de 2 o más de 64 caracteres.",
    "FEEDBACK_ACCOUNT_SUCCESSFULLY_CREATED" => "Su cuenta se ha creado correctamente y le hemos enviado un correo electrónico. Por favor haga clic en el ENLACE DE VERIFICACIÓN dentro de ese correo.",
    "FEEDBACK_VERIFICATION_MAIL_SENDING_FAILED" => "Lo sentimos, no pudimos enviarle un correo de verificación. Tu cuenta NO ha sido creada.",
    "FEEDBACK_ACCOUNT_CREATION_FAILED" => "Lo sentimos, tu registro falló. Por favor, regrese y vuelva a intentarlo.",
    "FEEDBACK_VERIFICATION_MAIL_SENDING_ERROR" => "No se pudo enviar el correo de verificación debido a:",
    "FEEDBACK_VERIFICATION_MAIL_SENDING_SUCCESSFUL" => "Un correo de verificación ha sido enviado con éxito.",
    "FEEDBACK_ACCOUNT_ACTIVATION_SUCCESSFUL" => "¡La activación fue exitosa! Ahora puede iniciar sesión.",
    "FEEDBACK_ACCOUNT_ACTIVATION_FAILED" => "Lo sentimos, no hay tal combinación de identificación / código de verificación aquí! Es posible que su proveedor de correo (Yahoo? Hotmail?) Visite automáticamente los enlaces en los correos electrónicos para el escaneo anti-estafa, por lo que se puede hacer clic en este enlace de activación sin su acción. Por favor, intente iniciar sesión en la página principal.",
    "FEEDBACK_AVATAR_UPLOAD_SUCCESSFUL" => "La carga del avatar fue exitosa.",
    "FEEDBACK_AVATAR_UPLOAD_WRONG_TYPE" => "Solo se admiten archivos JPEG y PNG.",
    "FEEDBACK_AVATAR_UPLOAD_TOO_SMALL" => "El ancho / alto del archivo fuente de Avatar es demasiado pequeño. Debe ser de 100x100 píxeles como mínimo.",
    "FEEDBACK_AVATAR_UPLOAD_TOO_BIG" => "El archivo fuente de Avatar es demasiado grande. 5 megabytes es el máximo.",
    "FEEDBACK_AVATAR_FOLDER_DOES_NOT_EXIST_OR_NOT_WRITABLE" => "La carpeta de avatar no existe o no se puede escribir. Por favor, cambie esto a través de chmod 775 o 777.",
    "FEEDBACK_AVATAR_IMAGE_UPLOAD_FAILED" => "Algo salió mal con la carga de la imagen.",
    "FEEDBACK_AVATAR_IMAGE_DELETE_SUCCESSFUL" => "Has eliminado correctamente tu avatar.",
    "FEEDBACK_AVATAR_IMAGE_DELETE_NO_FILE" => "No tienes un avatar personalizado.",
    "FEEDBACK_AVATAR_IMAGE_DELETE_FAILED" => "Algo salió mal al borrar tu avatar.",
    "FEEDBACK_PASSWORD_RESET_TOKEN_FAIL" => "No se pudo escribir el token a la base de datos.",
    "FEEDBACK_PASSWORD_RESET_TOKEN_MISSING" => "No hay token de restablecimiento de contraseña.",
    "FEEDBACK_PASSWORD_RESET_MAIL_SENDING_ERROR" => "El correo de restablecimiento de contraseña no se pudo enviar debido a:",
    "FEEDBACK_PASSWORD_RESET_MAIL_SENDING_SUCCESSFUL" => "Un correo de restablecimiento de contraseña ha sido enviado con éxito.",
    "FEEDBACK_PASSWORD_RESET_LINK_EXPIRED" => "Su enlace de restablecimiento ha caducado. Por favor use el enlace de reinicio dentro de una hora.",
    "FEEDBACK_PASSWORD_RESET_COMBINATION_DOES_NOT_EXIST" => "La combinación de nombre de usuario / código de verificación no existe.",
    "FEEDBACK_PASSWORD_RESET_LINK_VALID" => "El enlace de validación de restablecimiento de contraseña es válido. Por favor cambia la contraseña ahora.",
    "FEEDBACK_PASSWORD_CHANGE_SUCCESSFUL" => "Contraseña cambiada correctamente.",
    "FEEDBACK_PASSWORD_CHANGE_FAILED" => "Lo sentimos, tu cambio de contraseña falló.",
    "FEEDBACK_PASSWORD_NEW_SAME_AS_CURRENT" => "La nueva contraseña es la misma que la contraseña actual.",
    "FEEDBACK_PASSWORD_CURRENT_INCORRECT" => "La contraseña actual ingresada fue incorrecta.",
    "FEEDBACK_ACCOUNT_TYPE_CHANGE_SUCCESSFUL" => "Cambio de tipo de cuenta exitoso",
    "FEEDBACK_ACCOUNT_TYPE_CHANGE_FAILED" => "El cambio de tipo de cuenta falló",
    "FEEDBACK_NOTE_CREATION_FAILED" => "La creación de la nota falló.",
    "FEEDBACK_NOTE_EDITING_FAILED" => "La edición de notas falló.",
    "FEEDBACK_NOTE_DELETION_FAILED" => "La eliminación de la nota falló.",
    "FEEDBACK_COOKIE_INVALID" => "Tu cookie de recordarme no es válida.",
    "FEEDBACK_COOKIE_LOGIN_SUCCESSFUL" => "Has iniciado sesión correctamente a través de la cookie recordarme.",
    "FEEDBACK_EMPRESA_DELETION_SUCCESS" => "Empresa eliminada",
    "FEEDBACK_EMPRESA_DELETION_FAILED" => "No puede eliminar esta empresa, debe tener al menos una empresa",
    "FEEDBACK_EMPRESA_DELETION_UNKNOWN_ERROR" => "La eliminación de la empresa falló.",
    "FEEDBACK_EMPRESA_CREATION_SUCCESS" => "Se creo la empresa, ahora agregue más datos con el botón modificar.",
    "FEEDBACK_EMPRESA_CREATION_FAILED" => "Falló al crear la empresa, debe escribir un nombre de fantasia.",
    "FEEDBACK_EMPRESA_CREATION_UNKNOWN_ERROR" => "La creación de la empresa falló.",
    "FEEDBACK_EMPRESA_EDITING_SUCCESS" => "Se han guardado sus cambios.",
    "FEEDBACK_EMPRESA_EDITING_FAILED" => "No se pudieron guardar sus cambios.",
    "FEEDBACK_EMPRESA_CREATION_MAX" => "Ya has creado el máximo de empresas permitidas para tu cuenta, contacta al administrador",
    "FEEDBACK_EMPLEADO_EXIST" => "Este empleado ya existe en su empresa, use el cuadro búsqueda o revise a los empleados ocultos"
);
